services:
  app:
    image: debian:trixie-slim@sha256:77ba0164de17b88dd0bf6cdc8f65569e6e5fa6cd256562998b62553134a00ef0
    network_mode: "container:vpn"
    depends_on:
      - redis
    
  redis:
    image: redis:8.4.0-bookworm@sha256:73dad4271642c5966db88db7a7585fae7cf10b685d1e48006f31e0294c29fdd7
    networks:
      - vpn

networks:
  vpn:
    external: true
